#!/bin/sh


ucurl() {
    curl -L -g -s --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36' -H 'Accept-Encoding: gzip, deflate' --compressed "$@"
}

get_json() {
    ucurl "$1" | hgrep 'script +type="application/json" @p"%i\n"' | jq -cM '.props.pageProps | del(.mainColumnData.moreLikeThisTitles) | del(.mainColumnData.connections) | del(.requestContext) | del(.cmsContext) | del(.translationContext)'
}

#export -f ucurl get_json
#export PARALLEL_SHELL="$(type -p 'bash')"

g='0'
while :
do
    links="$(ucurl "https://www.imdb.com/sitemap/title-$g.xml.gz" | hgrep 'loc @p"%i\n"')"
    echo "$links" | grep -q '^<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message>' && break
    
    for j in $links
    do
        get_json "$j"
    done
    #echo "$links" | parallel -j 16 'get_json {}'
    ((g++))
done
